export const CHANGE_SEARCH_fIELD = 'CHANGE_SEARCH_fIELD';
export const REQUEST_COURSES_PENDING = 'REQUEST_COURSES_PENDING';
export const REQUEST_COURSES_SUCCESS = 'REQUEST_COURSES_SUCCESS';
export const REQUEST_COURSES_FAILED = 'REQUEST_COURSES_FAILED';